#!/bin/bash

set -e

OUTPUT_DIR='log'

file_he="$OUTPUT_DIR/1-file_list-helpers.txt"
file_mo="$OUTPUT_DIR/1-file_list-models.txt"
file_co="$OUTPUT_DIR/1-file_list-controllers.txt"
file_vi="$OUTPUT_DIR/1-file_list-views.txt"

echo '------------------------------------'
echo 'Listing the helper files in the file'
echo $file_he
echo 'This file was AUTOMATICALLY generated by the outline-short.sh script.' > $file_he
echo '-------------------' >> $file_he
echo 'HELPERS' >> $file_he
tree test/helpers >> $file_he
echo '' >> $file_he
tree app/helpers >> $file_he
echo '' >> $file_he

echo '-----------------------------------'
echo 'Listing the model files in the file'
echo $file_mo
echo 'This file was AUTOMATICALLY generated by the outline-short.sh script.' > $file_mo
echo '------' >> $file_mo
echo 'MODELS' >> $file_mo
tree test/models >> $file_mo
echo '' >> $file_mo
tree test/fixtures >> $file_mo
echo '' >> $file_mo
tree app/models >> $file_mo

echo '----------------------------------------'
echo 'Listing the controller files in the file'
echo $file_co
echo 'This file was AUTOMATICALLY generated by the outline-short.sh script.' > $file_co
echo '-----------' >> $file_co
echo 'CONTROLLERS' >> $file_co
tree test/controllers >> $file_co
echo '' >> $file_co
tree app/controllers >> $file_co

echo 'This file was AUTOMATICALLY generated by the outline-short.sh script.' > $file_vi
echo '---------------------------' >> $file_vi
echo 'VIEWS AND INTEGRATION TESTS' >> $file_vi
echo '' >> $file_vi
echo '----------------' >> $file_vi
echo 'config/routes.rb' >> $file_vi
cat config/routes.rb >> $file_vi
echo '----------------' >> $file_vi
tree test/integration >> $file_vi
echo '' >> $file_vi
tree app/views >> $file_vi

echo '------------------------------'
echo 'outline-short.sh OUTPUT FILES:'
echo $file_he
echo $file_mo
echo $file_co
echo $file_vi
echo

