#!/bin/bash
set +e

docker-compose down -v --remove-orphans
wait
echo '###########################'
echo 'BEGIN: docker-compose build'
echo '###########################'
docker-compose build
echo '##############################'
echo 'FINISHED: docker-compose build'
echo '##############################'

echo '----------------------------------------------------------------------------------------'
echo 'mkdir -p /home/winner/bundle/vendor && chown -R winner:winner /home/winner/bundle/vendor'
docker-compose run --rm -u root web bash -c 'mkdir -p /home/winner/bundle/vendor && chown -R winner:winner /home/winner/bundle/vendor'

echo '------------------------------------------------'
echo 'bundle install --path /home/winner/bundle/vendor'
docker-compose run --rm web bundle install --path /home/winner/bundle/vendor

echo '---------------------------'
echo 'bundle exec rake db:migrate'
docker-compose run --rm web bundle exec rake db:migrate
