#!/bin/bash

set -e

#POSTGRES#echo '------------------------------------'
#POSTGRES#echo 'docker-compose run --rm database env'
#POSTGRES#docker-compose run --rm database env

#POSTGRES#echo '-----------------------------------------------'
#POSTGRES#echo 'docker-compose run --rm database psql --version'
#POSTGRES#docker-compose run --rm database psql --version

echo '---'
echo 'env'
docker-compose run --rm web env

echo '-------------------'
echo 'cat /etc/os-release'
docker-compose run --rm web cat /etc/os-release

echo '-------'
echo 'ruby -v'
docker-compose run --rm web ruby -v

echo '--------------'
echo 'node --version'
docker-compose run --rm web node --version
