#!/bin/sh

set -e

bin/dbundle
bin/dmigrate
echo '--------------------------------------------'
echo 'rm -f /home/winner/myapp/tmp/pids/server.pid'
docker-compose run --rm web rm -f /home/winner/myapp/tmp/pids/server.pid

echo '--------------------------------------'
echo 'View this app at http://localhost:3000'
#MAILCATCHER#echo 'and the MailCatcher interface at http://localhost:1080'
echo ''
docker-compose up web
