version: "2"

services:
  web:
    build: .
    volumes:
      - .:/app
      - bundle_path:/bundle
    environment:
      - BUNDLE_PATH=/bundle/vendor
      - BUNDLE_APP_CONFIG=/app/.bundle
    user: winner
    command:
      - bundle
      - exec
      - rails
      - server
      - --binding=0.0.0.0
      - --port=3000

    ports:
      - "3000:3000"

volumes:
  bundle_path:
