.build: &build_definition
  before_script:
    - git config --global user.email "you@example.com"
    - git config --global user.name "Your Name"
    - apt-get update && apt-get install -y nodejs curl tree sudo postgresql graphviz
    - gem install rake
    - gem install rails
  script:
    - sh exec-main.sh 'tmp1' 'no_outline'
    - cd tmp1 && sh build_fast.sh
  stage: build

build_ruby_latest:
  <<: *build_definition
  image: ruby:latest

build_ruby_2_6_0:
  <<: *build_definition
  image: ruby:2.6.0
