.build: &build_definition
  before_script:
    - DIR_MAIN=$PWD
    - DIR_PARENT="$(dirname "$DIR_MAIN")"
    - git config --global user.email "you@example.com"
    - git config --global user.name "Your Name"
    - apt-get update && apt-get install -y nodejs
    - gem install rake
    - gem install rails
  script:
    - sh exec-main.sh 'tmp1' 'no_outline'
    - cd $DIR_PARENT/tmp1 && sh neutrino.sh
  stage: build

build_ruby_2_6_0:
  <<: *build_definition
  image: ruby:2.6.0

build_ruby_2_6_3:
  <<: *build_definition
  image: ruby:2.6.3
