services:
  - docker

before_script:
  - sudo apt-get install -y bash
  - gem uninstall -i /home/travis/.rvm/gems/ruby-*@global bundler

script:
  - $PWD/build-rails 'tmp1'

after_script:
  - cd $PWD/tmp1 && bundle install && rails db:migrate && rails test
