#!/bin/bash
set -e

# NOTE: This script is used ONLY in the continuous integration environment
# and is NOT intended for the development environment on your local machine.

# BEGIN: activate NVM
export NVM_DIR="/home/`whoami`/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
# END: activate NVM

nvm use node # Activate Node

source ~/.rvm/scripts/rvm # Activate RVM

git config --global user.email "you@example.com"
git config --global user.name "Your Name"

sh exec-main.sh 'tmp1' 'no_outline'
