#!/bin/bash

# This script is used to test the new app generated by Rails Neutrino.
# It's similar to build_fast.sh, but some steps are skipped to save time.

#!/bin/bash

sh pg-start.sh
sh kill_spring.sh
sh test_app.sh

echo '----------------------'
echo 'bundle install --quiet'
bundle install --quiet

# Checks for security vulnerabilities
# -A: runs all checks
# -q: output the report only; suppress information warnings
# -w2: level 2 warnings (medium and high only)
echo '----------------------------'
echo 'bundle exec brakeman -Aq -w2'
bundle exec brakeman -Aq -w2

# Checks for compliance with Sandi Metz' four rules
echo '-----------------------'
echo 'bundle exec sandi_meter'
bundle exec sandi_meter

# Update the local ruby-advisory-db advisory database
echo '-------------------------------'
echo 'bundle exec bundle-audit update'
bundle exec bundle-audit update

# Audit the gems listed in Gemfile.lock for vulnerabilities
echo '------------------------'
echo 'bundle exec bundle-audit'
bundle exec bundle-audit

# Checks for violations of the Ruby Style Guide, not recommended for legacy apps
echo '----------------------'
echo 'bundle exec rubocop -D'
bundle exec rubocop -D

# Checks the quality of Rails code, not recommended for legacy apps
echo '----------------------------------'
echo 'bundle exec rails_best_practices .'
bundle exec rails_best_practices .
