#!/bin/sh

set -e

# Checks the quality of Rails code, not recommended for legacy apps
echo '----------------------------------'
echo 'bundle exec rails_best_practices .'
docker-compose run --rm web bundle exec rails_best_practices .
