#!/usr/bin/ruby

require 'insert_from_file'
require 'line_containing'
require 'string_in_file'
require 'gemfile_entry'

puts 'Adding ransack to the Gemfile'
InsertFromFile.add_end('mod-09-05-Gemfile.txt', 'Gemfile')
puts 'bundle install --quiet'
system('bundle install --quiet')
StringInFile.replace("gem 'ransack'", "#{GemfileEntry.active('ransack')}", 'Gemfile')
puts 'bundle install --quiet'
system('bundle install --quiet')

puts 'Updating config/routes.rb'
InsertFromFile.add_before('mod-09-05-routes.txt', 'config/routes.rb', '# END: user section')

puts 'Updating app/controllers/users_controller.rb'
InsertFromFile.replace_between('mod-09-05-users_controller.txt', 'app/controllers/users_controller.rb', '# BEGIN: index', '# END: index')

puts 'Updating app/views/users/index.html.erb'
InsertFromFile.add_before('mod-09-05-index.txt', 'app/views/users/index.html.erb', '<h1>User Index</h1>')

puts 'Adding app/views/users/_condition_fields.html.erb'
system('mv mod-09-05-_condition_fields.html.erb app/views/users/_condition_fields.html.erb')

puts 'Updating app/helpers/application_helper.rb'
InsertFromFile.add_after('mod-09-05-application_helper.txt', 'app/helpers/application_helper.rb', '# END: full_title')

puts 'Updating app/assets/javascripts/users.coffee'
InsertFromFile.add_end('mod-09-05-users_coffee.txt', 'app/assets/javascripts/users.coffee')

puts 'Updating app/models/user.rb'
InsertFromFile.add_after('mod-09-05-user.txt', 'app/models/user.rb', 'class User < ApplicationRecord')

puts 'Updating config/rails_best_practices.yml'
LineContaining.replace('MoveModelLogicIntoModelCheck', "MoveModelLogicIntoModelCheck: { ignored_files: ['app/controllers/users_controller.rb'] }", 'config/rails_best_practices.yml')
LineContaining.replace('RestrictAutoGeneratedRoutesCheck', "RestrictAutoGeneratedRoutesCheck: { ignored_files: ['config/routes.rb'] }", 'config/rails_best_practices.yml')
